apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    app: api
    org: cloudacademy
  namespace: cloudacademy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
      org: cloudacademy
  template:
    metadata:
      labels:
        app: api
        org: cloudacademy
    spec:
      containers:
      - name: api
        image: cloudacademydevops/api-metrics
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    app: api
    org: cloudacademy
  namespace: cloudacademy
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "5000"
spec:
  ports:
  - port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: api
    org: cloudacademy
  type: NodePort